# Generated by Django 4.2.1 on 2023-06-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='file',
            new_name='art_file',
        ),
    ]
