# Generated by Django 4.2.1 on 2023-06-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_file_artwork_art_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'ordering': ['-artist_id']},
        ),
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
    ]
